name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.72.0'
          extended: true

      - name: Build
        working-directory: ./src
        run: hugo --gc --minify --cleanDestinationDir --destination="../public"

      - name: CNAME
        run: echo "alsmnd.com" > ./public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.HUGO_PAGE }}
          publish_dir: ./public
          publish_branch: gh-pages